---
services:
  homeassistant:
    container_name: zte-dev-ha
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      # Mount the whole project so the DevContainer workspace works
      - ..:/workspaces/ha-zte-router-5g-monitor
      # Mount your local dev config
      - ./.devconfig:/config
      # IMPORTANT: Use a relative path from the
      #  project root inside the container
      # This ensures HA sees your code as an integration
      - ../custom_components/zte_router_5g:/config/custom_components/zte_router_5g:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment:
      - TZ=Europe/London
