---
name: Validate

"on":
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Daily at midnight

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    permissions:
      contents: write # Required by test_val for coverage badge gist update
      pull-requests: write # Required by test_val for PR comments
    # Branch @main v1.0.9
    uses: PlayFaster/.github/.github/workflows/validate.yaml@8b0597a4d577fe429ba1b3faf7598e2279d77286
    with:
      component_name: zte_router_5g
      gist_id: 0376d580e72d0abc493665a80396f701
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
